apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    component: kafka-broker
spec:
  ports:
  - port: 9095
    name: kafka-port
    targetPort: 9095
    protocol: TCP
  selector:
    app: kafka
    component: kafka-broker